### ISSUE TITLE
Crash relating to AdvancedHolograms

### ISSUE THREAD

**Issue by monatizd** [Pixelmon-Development/AdvancedHolograms#3]
Server is running the latest (0.2.0) and we're getting this crash occasionally when we make holograms. Here's our crash report:

https://hastebin.com/etadosanew.yaml

both crash reports are the same error.

**Comment by danorris709** [comment]
Fixed in https://github.com/Pixelmon-Development/API/commit/99044dc70297dfe1dd16db450c371f460fe8b55d
Working on a release soon with placeholders. Apologies for the delay

**Comment by danorris709** [comment]
Latest release has the patch
