### ISSUE TITLE
Modify Missing World Error

### ISSUE THREAD

**Issue by ghost** [Pixelmon-Development/AdvancedHolograms#5]
Can the AdvancedHolograms error be modified so it gracefully error if a world is missing instead of crashing the server.

**Comment by danorris709** [comment]
If the world is missing this is a critical issue. There really isn't a solution where it can "gracefully error"

**Comment by ChipWolf** [comment]
Gracefully error by not loading the holograms, you could also provide a command to remap the world while the server is running

**Comment by ghost** [comment]
This issue is still occuring

**Comment by danorris709** [comment]
You've been told how to fix this. There is no "graceful" error for a world not being found.
